# Generated by Django 2.0 on 2020-01-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c',
            name='EUR',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='c',
            name='IQD',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='c',
            name='MAD',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='c',
            name='USD',
            field=models.FloatField(),
        ),
    ]
