# Generated by Django 2.0 on 2020-01-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200113_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='usd_to_currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USD', models.FloatField()),
                ('IQD', models.FloatField()),
                ('EUR', models.FloatField()),
                ('MAD', models.FloatField()),
            ],
        ),
    ]
