# Generated by Django 2.0 on 2020-01-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_usd_to_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='dec_currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USD', models.TextField()),
                ('IQD', models.TextField()),
                ('EUR', models.TextField()),
                ('MAD', models.TextField()),
            ],
        ),
    ]
